<?xml version="1.0" encoding="utf-8"?><Database Name="IdeaMachine" Class="IdeaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=IdeaMachine.db.10021657.hostedresource.com;Initial Catalog=IdeaMachine;Persist Security Info=True;User ID=IdeaMachine" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="IdeaMachineConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.idea" Member="ideas">
    <Type Name="idea">
      <Column Name="guid" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="author" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="up_for_grabs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="claimer" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="created_at" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="inappropriate" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>